# .github/workflows/list-files.yml
name: List Files

on:
  push:
    branches:
      - main

jobs:
  list:
    runs-on: [self-hosted]
    steps:
      - name: List working directory
        run: ls -la

